// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"UnifiedInfraTopology/internal/handler"
	"UnifiedInfraTopology/internal/repository"
	"UnifiedInfraTopology/internal/router"
	"UnifiedInfraTopology/internal/server"
	"UnifiedInfraTopology/internal/service"
	"UnifiedInfraTopology/pkg/app"
	"UnifiedInfraTopology/pkg/jwt"
	"UnifiedInfraTopology/pkg/log"
	"UnifiedInfraTopology/pkg/server/http"
	"UnifiedInfraTopology/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	inventoryRepository := repository.NewInventoryRepository(repositoryRepository)
	inventoryService := service.NewInventoryService(inventoryRepository, viperViper)
	inventoryHandler := handler.NewInventoryHandler(handlerHandler, inventoryService)
	routerDeps := router.RouterDeps{
		Logger:           logger,
		Config:           viperViper,
		JWT:              jwtJWT,
		UserHandler:      userHandler,
		InventoryHandler: inventoryHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewInventoryRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewInventoryService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewInventoryHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

// build App
func newApp(
	httpServer *http.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("unified-infra-topology"))
}
