// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"UnifiedInfraTopology/internal/repository"
	"UnifiedInfraTopology/internal/server"
	"UnifiedInfraTopology/pkg/log"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*server.MigrateServer, func(), error) {
	db := repository.NewDB(viperViper, logger)
	migrateServer := server.NewMigrateServer(db, logger)
	return migrateServer, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB)

var serverSet = wire.NewSet(server.NewMigrateServer)
