// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"UnifiedInfraTopology/internal/adapter"
	"UnifiedInfraTopology/internal/service"
	"UnifiedInfraTopology/pkg/log"
)

// Injectors from wire.go:

// NewWire 不装配 HTTP、数据库、迁移或图客户端；基础版没有外部写入能力。
func NewWire(logger *log.Logger) (*service.SyncWorker, error) {
	cmdb := adapter.NewCMDB()
	syncWorker := service.NewSyncWorker(cmdb, logger)
	return syncWorker, nil
}
